/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SyllabusRouteImport } from './routes/syllabus'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as LecturesRouteImport } from './routes/lectures'
import { Route as FlowchartRouteImport } from './routes/flowchart'
import { Route as CheatsheetRouteImport } from './routes/cheatsheet'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyIndexRouteImport } from './routes/verify.index'
import { Route as VerifyIdRouteImport } from './routes/verify.$id'
import { Route as LectureIdRouteImport } from './routes/lecture.$id'

const SyllabusRoute = SyllabusRouteImport.update({
  id: '/syllabus',
  path: '/syllabus',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturesRoute = LecturesRouteImport.update({
  id: '/lectures',
  path: '/lectures',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowchartRoute = FlowchartRouteImport.update({
  id: '/flowchart',
  path: '/flowchart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheatsheetRoute = CheatsheetRouteImport.update({
  id: '/cheatsheet',
  path: '/cheatsheet',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIndexRoute = VerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIdRoute = VerifyIdRouteImport.update({
  id: '/verify/$id',
  path: '/verify/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LectureIdRoute = LectureIdRouteImport.update({
  id: '/lecture/$id',
  path: '/lecture/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/flowchart': typeof FlowchartRoute
  '/lectures': typeof LecturesRoute
  '/playground': typeof PlaygroundRoute
  '/syllabus': typeof SyllabusRoute
  '/lecture/$id': typeof LectureIdRoute
  '/verify/$id': typeof VerifyIdRoute
  '/verify/': typeof VerifyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/flowchart': typeof FlowchartRoute
  '/lectures': typeof LecturesRoute
  '/playground': typeof PlaygroundRoute
  '/syllabus': typeof SyllabusRoute
  '/lecture/$id': typeof LectureIdRoute
  '/verify/$id': typeof VerifyIdRoute
  '/verify': typeof VerifyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/flowchart': typeof FlowchartRoute
  '/lectures': typeof LecturesRoute
  '/playground': typeof PlaygroundRoute
  '/syllabus': typeof SyllabusRoute
  '/lecture/$id': typeof LectureIdRoute
  '/verify/$id': typeof VerifyIdRoute
  '/verify/': typeof VerifyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cheatsheet'
    | '/flowchart'
    | '/lectures'
    | '/playground'
    | '/syllabus'
    | '/lecture/$id'
    | '/verify/$id'
    | '/verify/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cheatsheet'
    | '/flowchart'
    | '/lectures'
    | '/playground'
    | '/syllabus'
    | '/lecture/$id'
    | '/verify/$id'
    | '/verify'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cheatsheet'
    | '/flowchart'
    | '/lectures'
    | '/playground'
    | '/syllabus'
    | '/lecture/$id'
    | '/verify/$id'
    | '/verify/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CheatsheetRoute: typeof CheatsheetRoute
  FlowchartRoute: typeof FlowchartRoute
  LecturesRoute: typeof LecturesRoute
  PlaygroundRoute: typeof PlaygroundRoute
  SyllabusRoute: typeof SyllabusRoute
  LectureIdRoute: typeof LectureIdRoute
  VerifyIdRoute: typeof VerifyIdRoute
  VerifyIndexRoute: typeof VerifyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/syllabus': {
      id: '/syllabus'
      path: '/syllabus'
      fullPath: '/syllabus'
      preLoaderRoute: typeof SyllabusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lectures': {
      id: '/lectures'
      path: '/lectures'
      fullPath: '/lectures'
      preLoaderRoute: typeof LecturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flowchart': {
      id: '/flowchart'
      path: '/flowchart'
      fullPath: '/flowchart'
      preLoaderRoute: typeof FlowchartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cheatsheet': {
      id: '/cheatsheet'
      path: '/cheatsheet'
      fullPath: '/cheatsheet'
      preLoaderRoute: typeof CheatsheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/': {
      id: '/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof VerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$id': {
      id: '/verify/$id'
      path: '/verify/$id'
      fullPath: '/verify/$id'
      preLoaderRoute: typeof VerifyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecture/$id': {
      id: '/lecture/$id'
      path: '/lecture/$id'
      fullPath: '/lecture/$id'
      preLoaderRoute: typeof LectureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CheatsheetRoute: CheatsheetRoute,
  FlowchartRoute: FlowchartRoute,
  LecturesRoute: LecturesRoute,
  PlaygroundRoute: PlaygroundRoute,
  SyllabusRoute: SyllabusRoute,
  LectureIdRoute: LectureIdRoute,
  VerifyIdRoute: VerifyIdRoute,
  VerifyIndexRoute: VerifyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
